// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD92dB2zU5mQdkNUCccE6N0iopSI9bnuJs',
    appId: '1:355957368749:web:8fd13438b39011302e2324',
    messagingSenderId: '355957368749',
    projectId: 'delaure-11c79',
    authDomain: 'delaure-11c79.firebaseapp.com',
    storageBucket: 'delaure-11c79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2gO6XaZuy1paAEhxs1CR3-yYY0qO3Dg',
    appId: '1:355957368749:android:378184eb13bcdc0c2e2324',
    messagingSenderId: '355957368749',
    projectId: 'delaure-11c79',
    storageBucket: 'delaure-11c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApT3LOfVidd17R8I84Xi-uBTKERgG-05U',
    appId: '1:355957368749:ios:3848313ff491d6ac2e2324',
    messagingSenderId: '355957368749',
    projectId: 'delaure-11c79',
    storageBucket: 'delaure-11c79.appspot.com',
    iosBundleId: 'com.example.newBerry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApT3LOfVidd17R8I84Xi-uBTKERgG-05U',
    appId: '1:355957368749:ios:e31ae16f58305f502e2324',
    messagingSenderId: '355957368749',
    projectId: 'delaure-11c79',
    storageBucket: 'delaure-11c79.appspot.com',
    iosBundleId: 'com.example.newBerry.RunnerTests',
  );
}
